FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=pulsar/pulsar
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY pulsar.tar.gz /pulsar.tar.gz
RUN tar -xvf /pulsar.tar.gz

#ADD . /pulsar
RUN cd /pulsar/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /pulsar && scripts/windows-crosscompile/compile-pulsar.sh
